[package]
name = "lw-lwnx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["impl-default", "ioapiset"] }
# winapi = "0.3.9"
serialport = "4"